name: Run tests

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.4, 7.3, 7.2, 7.1]
        laravel: [8, 7, 6, 5.8, 5.7, 5.6, 5.5]
        include:
          - laravel: 8
            testbench: 6
          - laravel: 7
            testbench: 5
            remove: "laravel/legacy-factories"
          - laravel: 6
            testbench: 4
            remove: "laravel/legacy-factories"
          - laravel: 5.8
            testbench: 3.8
            remove: "laravel/legacy-factories"
          - laravel: 5.7
            testbench: 3.7
            remove: "laravel/legacy-factories"
          - laravel: 5.6
            testbench: 3.6
            remove: "laravel/legacy-factories"
          - laravel: 5.5
            testbench: 3.5
            remove: "laravel/legacy-factories"
        exclude:
          - laravel: 8
            php: 7.2
          - laravel: 8
            php: 7.1
          - laravel: 7
            php: 7.2
          - laravel: 7
            php: 7.1
          - laravel: 6
            php: 7.1

    name: PHP:${{ matrix.php }} - Laravel:${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer remove "${{ matrix.remove }}" --no-update --ignore-platform-reqs
          composer require "laravel/framework:${{ matrix.laravel }}.*" "orchestra/testbench:${{ matrix.testbench }}.*" --no-interaction --no-update --dev
          composer update --prefer-stable --prefer-dist --no-interaction --no-suggest

      - name: Run Tests
        run: vendor/bin/phpunit --configuration phpunit.xml.dist
